# Generated by Django 5.0 on 2023-12-30 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answersheet',
            name='question_paper',
        ),
        migrations.RemoveField(
            model_name='answersheet',
            name='student',
        ),
        migrations.RemoveField(
            model_name='session',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='studentfeedback',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentleave',
            name='student',
        ),
        migrations.RemoveField(
            model_name='teacherfeedback',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='TeacherJob',
        ),
        migrations.DeleteModel(
            name='AnswerSheet',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='StudentFeedback',
        ),
        migrations.DeleteModel(
            name='StudentLeave',
        ),
        migrations.DeleteModel(
            name='TeacherFeedback',
        ),
    ]
