# Generated by Django 5.0 on 2024-01-01 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0002_remove_answersheet_question_paper_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
