# Generated by Django 5.0 on 2024-01-01 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0003_delete_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
    ]
