# Generated by Django 5.0 on 2024-01-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0004_remove_student_user_remove_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherleave',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
