# Generated by Django 5.0 on 2024-01-02 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0005_teacherleave_is_rejected'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentAdmission',
        ),
    ]
