# Generated by Django 5.0 on 2024-01-08 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0009_remove_attendance_is_present_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Class',
        ),
    ]
